package com.cluster;

// Generated Oct 21, 2014 4:34:40 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department",catalog="userdb")
public class Department implements java.io.Serializable {

	private int deptid;
	private String dname;
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Department() {
	}

	public Department(int deptid) {
		this.deptid = deptid;
	}

	public Department(int deptid, String dname, Set<Employee> employees) {
		this.deptid = deptid;
		this.dname = dname;
		this.employees = employees;
	}

	@Id
	@Column(name = "DEPTID", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getDeptid() {
		return this.deptid;
	}

	public void setDeptid(int deptid) {
		this.deptid = deptid;
	}

	@Column(name = "DNAME", length = 20)
	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department",cascade=CascadeType.ALL)
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
