package com.cluster;

// Generated Oct 21, 2014 4:34:40 PM by Hibernate Tools 4.0.0

import javax.annotation.Generated;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GeneratorType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee",catalog="test")
public class Employee implements java.io.Serializable {

	private int empid;
	private Department department;
	private String ename;
	private String email;

	public Employee() {
	}

	public Employee(int empid) {
		this.empid = empid;
	}

	public Employee(int empid, Department department, String ename, String email) {
		this.empid = empid;
		this.department = department;
		this.ename = ename;
		this.email = email;
	}

	@Id
	@Column(name = "EMPID", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public int getEmpid() {
		return this.empid;
	}

	public void setEmpid(int empid) {
		this.empid = empid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPTID")
	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	@Column(name = "ENAME", length = 20)
	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	@Column(name = "EMAIL", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
