DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT
(
DEPTID INT(5) PRIMARY KEY AUTO_INCREMENT,
DNAME VARCHAR(20)
);

CREATE TABLE EMPLOYEE
(
EMPID INT(5) PRIMARY KEY AUTO_INCREMENT,
ENAME VARCHAR(20),
EMAIL VARCHAR(30),
DEPTID INT(5), 
FOREIGN KEY(DEPTID) 
REFERENCES DEPARTMENT(DEPTID)
);